package com.crm.users.Exception;

public enum Exception {
    ROLES_EXCEPTION,
    USERS_EXCEPTION,
    ROLE_AUTHORITIES_EXCEPTION,
    AUTHORITIES_EXCEPTION,
    INVALID_ARGUMENTS,
    USER_AUTHORITIES_EXCEPTION,
    AUTHENTICATION_FAILED
}
